### ISSUE TITLE
Refactor MasterForm.svelte

### ISSUE THREAD

**Issue by edenriquez** [edenriquez/svelte-multistep-form#14]
Refactor functions inside this file in a separated helpers or commons .js (name is up to you) file which
- should contain all repeated logic.
- should declare all static variables into a constants file and import them.
- add some unit tests for all helpers.

**Comment by tobsfit** [comment]
Hi @edenriquez, I can work on this issue. Let me know if it's okay for you. 
Kind regards

**Comment by tobsfit** [comment]
Do I need a special setup? I checkout the `example` folder and installed all the dependencies. After running `npm run dev` I got an 404 error.

**Comment by edenriquez** [comment]
sorry yes I notice that, let me check where is the issue

**Comment by tobsfit** [comment]
Thanks for your investigation! :)

**Comment by edenriquez** [comment]
Hey @tobsfit seems like since I was including `public` directory inside the .gitignore it was not committing `/build` (which is great) but also it was not including `/public/index.html` which should call all assets inside `build` so I already added the whole public folder now you can just pull again and run it, let me know if there is anything else that comes up :)

**Comment by tobsfit** [comment]
Hey @edenriquez. Thanks for the provided fix. Now, it works smoothly. I will let you know if this changes. :)

**Comment by edenriquez** [comment]
this issues is fixed
