### ISSUE TITLE
Export nextStep() to allow programatic control

### ISSUE THREAD

**Issue by chris-aeviator** [edenriquez/svelte-multistep-form#23]
I think it would be useful to allow to trigger switching to the next step programatically (e.g. after validating an entry).

Therefore an `export` should be added to https://github.com/edenriquez/svelte-multistep-form/blob/5635ccc8f9b235565c866959366524d6bddabcb4/src/MasterForm.svelte#L42 .

This way people can reference the form in their own code

```

<Form bind:this={myForm} {multiStepOptions}>
```

and run `myForm.nextStep()`

**Comment by edenriquez** [comment]
This is already in version 0.0.6, thanks for the suggestion @chris-aeviator  👍
